### TESTING SERVER ROUTE

GET http://localhost:4000


### REGISTER

POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "firstName": "Marija",
  "lastName": "Marijana",
  "userName": "Maki",
  "email": "maki@gmail.com",
  "password": "maki"
}


### LOGIN

POST http://localhost:4000/api/auth/login
Content-Type:  application/json

{
     
    "userName": "hmoa",
    "password": "12345"
}