

### SUPER ADMIN DASHBOARD   

GET http://localhost:4000/api/dashboard/superAdmin/64a7399783748126f8550e85
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE5NmMwOGJlYWNlMWNkYTQzOGVmOWYiLCJmaXJzdE5hbWUiOiJaZHJhdmtvIiwibGFzdE5hbWUiOiJSaXN0aWMiLCJ1c2VyTmFtZSI6InpkcmF2a28iLCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY4OTQ0ODY1MCwiZXhwIjoxNjkyMDQwNjUwfQ.84cfiDeUOxGXb_scLf7tU0gOJGreU4-6hQc6qqds6Bs