### GET ALL RACES

GET http://localhost:4000/api/race/all

###  ADD RACE 

POST http://localhost:4000/api/race/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE3Mzk5NzgzNzQ4MTI2Zjg1NTBlODUiLCJmaXJzdE5hbWUiOiJBaG1lZCIsImxhc3ROYW1lIjoiTGVtZXMiLCJ1c2VyTmFtZSI6Imhtb2EiLCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY4OTM0NDQ5NiwiZXhwIjoxNjg5NDMwODk2fQ.iK7WRDiHLayzj1QvGcKgbByUG-pEjtRIaXlerriAqLI

{
    "name": "trka na Adi",
    "dateOfRace": "2021-10-10",
    "location": "Tara",
    "description": "10km",
    "startTime": "10:00",
    "endTime": "12:00",
    "welcomePackage": false
}

### ASSIGN ADMIN AND USERS TO RACE

POST http://localhost:4000/api/race/assign
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE5NmMwOGJlYWNlMWNkYTQzOGVmOWYiLCJmaXJzdE5hbWUiOiJaZHJhdmtvIiwibGFzdE5hbWUiOiJSaXN0aWMiLCJ1c2VyTmFtZSI6InpkcmF2a28iLCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY4OTQ0ODY1MCwiZXhwIjoxNjkyMDQwNjUwfQ.84cfiDeUOxGXb_scLf7tU0gOJGreU4-6hQc6qqds6Bs

### EDIT RACE

PUT http://localhost:4000/api/race/64afff0498ae6356280242d4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE5NmMwOGJlYWNlMWNkYTQzOGVmOWYiLCJmaXJzdE5hbWUiOiJaZHJhdmtvIiwibGFzdE5hbWUiOiJSaXN0aWMiLCJ1c2VyTmFtZSI6InpkcmF2a28iLCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY4OTQ0ODY1MCwiZXhwIjoxNjkyMDQwNjUwfQ.84cfiDeUOxGXb_scLf7tU0gOJGreU4-6hQc6qqds6Bs

{
    "name": "izmenjena trka"
}


### DELETE RACE

DELETE http://localhost:4000/api/race/64b2ab019c14324d9f4ed42f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE5NmMwOGJlYWNlMWNkYTQzOGVmOWYiLCJmaXJzdE5hbWUiOiJaZHJhdmtvIiwibGFzdE5hbWUiOiJSaXN0aWMiLCJ1c2VyTmFtZSI6InpkcmF2a28iLCJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY4OTQ0ODY1MCwiZXhwIjoxNjkyMDQwNjUwfQ.84cfiDeUOxGXb_scLf7tU0gOJGreU4-6hQc6qqds6Bs
